CREATE TABLE categoria (
    cod_categoria  INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre         VARCHAR2(100) NOT NULL
);

ALTER TABLE categoria ADD CONSTRAINT categoria_pk PRIMARY KEY ( cod_categoria );

CREATE TABLE ciudad (
    cod_ciudad         INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre             VARCHAR2(100) NOT NULL,
    region_cod_region  INTEGER NOT NULL
);

ALTER TABLE ciudad ADD CONSTRAINT ciudad_pk PRIMARY KEY ( cod_ciudad );

CREATE TABLE compania (
    cod_compania       INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_compania    VARCHAR2(100) NOT NULL,
    contacto_compania  VARCHAR2(100) NOT NULL,
    correo_compania    VARCHAR2(100) NOT NULL,
    telefono_compania  VARCHAR2(20) NOT NULL
);

ALTER TABLE compania ADD CONSTRAINT compania_pk PRIMARY KEY ( cod_compania );

CREATE TABLE orden (
    cod_orden              INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    compania_cod_compania  INTEGER NOT NULL,
    persona_id_persona     INTEGER NOT NULL
);

ALTER TABLE orden ADD CONSTRAINT orden_pk PRIMARY KEY ( cod_orden );

CREATE TABLE orden_producto (
    cantidad               INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    orden_cod_orden        INTEGER NOT NULL,
    producto_cod_producto  INTEGER NOT NULL
);

ALTER TABLE orden_producto ADD CONSTRAINT orden_producto_pk PRIMARY KEY ( orden_cod_orden,
                                                                          producto_cod_producto );

CREATE TABLE persona (
    id_persona         INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    tipo               CHAR(1) NOT NULL,
    nombre             VARCHAR2(100) NOT NULL,
    correo             VARCHAR2(100) NOT NULL,
    telefono           VARCHAR2(20) NOT NULL,
    fecha_registro     DATE NOT NULL,
    direccion          VARCHAR2(250) NOT NULL,
    codigo_postal      INTEGER NOT NULL,
    ciudad_cod_ciudad  INTEGER NOT NULL
);

ALTER TABLE persona ADD CONSTRAINT persona_pk PRIMARY KEY ( id_persona );

CREATE TABLE producto (
    cod_producto             INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre                   VARCHAR2(100) NOT NULL,
    precio_unitario          NUMBER(8, 2) NOT NULL,
    categoria_cod_categoria  INTEGER NOT NULL
);

ALTER TABLE producto ADD CONSTRAINT producto_pk PRIMARY KEY ( cod_producto );

CREATE TABLE region (
    cod_region  INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre      VARCHAR2(100) NOT NULL
);

ALTER TABLE region ADD CONSTRAINT region_pk PRIMARY KEY ( cod_region );

CREATE TABLE temp_informacion (
    nombre_compania     VARCHAR2(100),
    contacto_compania   VARCHAR2(100),
    correo_compania     VARCHAR2(100),
    telefono            VARCHAR2(20),
    tipo                VARCHAR2(1),
    nombre_persona      VARCHAR2(100),
    correo_persona      VARCHAR2(100),
    telefono_persona    VARCHAR2(20),
    fecha_registro      VARCHAR2(100),
    direccion           VARCHAR2(250),
    ciudad              VARCHAR2(100),
    codigo_postal       VARCHAR2(100),
    region              VARCHAR2(100),
    producto            VARCHAR2(100),
    categoria_producto  VARCHAR2(100),
    cantidad            VARCHAR2(100),
    precio_unitario     VARCHAR2(100)
);

ALTER TABLE ciudad
    ADD CONSTRAINT ciudad_region_fk FOREIGN KEY ( region_cod_region )
        REFERENCES region ( cod_region );

ALTER TABLE orden
    ADD CONSTRAINT orden_compania_fk FOREIGN KEY ( compania_cod_compania )
        REFERENCES compania ( cod_compania );

ALTER TABLE orden
    ADD CONSTRAINT orden_persona_fk FOREIGN KEY ( persona_id_persona )
        REFERENCES persona ( id_persona );

ALTER TABLE orden_producto
    ADD CONSTRAINT orden_producto_orden_fk FOREIGN KEY ( orden_cod_orden )
        REFERENCES orden ( cod_orden );

ALTER TABLE orden_producto
    ADD CONSTRAINT orden_producto_producto_fk FOREIGN KEY ( producto_cod_producto )
        REFERENCES producto ( cod_producto );

ALTER TABLE persona
    ADD CONSTRAINT persona_ciudad_fk FOREIGN KEY ( ciudad_cod_ciudad )
        REFERENCES ciudad ( cod_ciudad );

ALTER TABLE producto
    ADD CONSTRAINT producto_categoria_fk FOREIGN KEY ( categoria_cod_categoria )
        REFERENCES categoria ( cod_categoria );
ALTER TABLE persona
    ADD CONSTRAINT persona_ciudad_fk FOREIGN KEY ( ciudad_cod_ciudad )
        REFERENCES ciudad ( cod_ciudad );

ALTER TABLE producto
    ADD CONSTRAINT producto_categoria_fk FOREIGN KEY ( categoria_cod_categoria )
        REFERENCES categoria ( cod_categoria );
